src/components/TopBasicNav.css, src/components/TopBasicNav.jsx
상단 기본 nav 바 UI 완성했습니다
close #4
=> #4 - Feat: 기본 네비게이션 바 컴포넌트 개발

src/components/ChatItem.css, src/components/ChatItem.jsx, src/pages/ChatListPage.jsx
채팅 아이템과 채팅 목록 페이지 컴포넌트 완성했습니다!
내용 부분 말줄임 처리는 추후 구현 예정입니닷
close #2
=> #2 - Feat: 채팅 목록 컴포넌트 개발

public/index.html, src/App.jsx, src/components/modal/Logout.jsx, src/components/modal/ProfileModal.jsx, src/components/modal/modalAlert.css, src/components/modal/profileModal.css, src/reset.css
프로필에서 모달 클릭시 나오는 컴포넌트와 로그아웃 버튼 개발을 하였습니다!! 
closes #3
=> #3 - Feat:프로필 modal 컴포넌트 개발

src/components/TapMenu.css, src/components/TapMenu.jsx
하단 탭 메뉴 컴포넌트 입니다.
버튼으로 만든 부분을 추후 페이지들이 어느 정도 생기면 Link로 변경할 예정입니다.
close #5
=> #5 - Feat: 하단 탭 메뉴 컴포넌트 개발

src/App.jsx, src/components/modal/PostAlert.jsx, src/components/modal/PostModal.jsx, src/components/modal/ProductAlert.jsx, src/components/modal/ProductModal.jsx, src/components/modal/modalAlert.css
post, product 모달 컴포넌트 + alert창를 개발해보았습니다!  
closes #10
=> #10 - Feat:게시글 modal 컴포넌트 개발

src/pages/HomePage.css, src/pages/HomePage.jsx
빈 피드 화면 페이지 완성 했습니다.
HomePage.jsx
HomePage.css
close #11
=> #11 - Feat:빈 피드 화면 페이지

src/components/feed/TopSearchNav.css, src/components/feed/TopSearchNav.jsx
검색 컴포넌트 개발 완료했습니다.
[components]/[feed]/
TopSearchNav.jsx
TopSearchNav.css
close #16
=> #16 - Feat: 검색 컴포넌트 개발

src/components/chat/LeaveChatModal.css, src/components/chat/LeaveChatModal.jsx, src/components/modal/CommentModal.jsx, src/reset.css
컴포넌트 개발 완료했습니다.
기존에 있던 모달 css를 공유하기 위해서 CommentModal.jsx에서 profileModal.css를 참조하고 있습니다! 
close #19
=> #19 - Feat: 댓글 및 채팅방 모달 컴포넌트

src/pages/feed/UploadPost.css
아까... 냅다 머지했던 페이지 부분에 색상 변수 적용했습니다..🙏
close #24
=> #24 - Style: 게시글 작성 페이지 CSS 변수 적용

src/App.jsx, src/components/uploads/ProductUpload.css, src/components/uploads/ProductUpload.jsx
상품 등록 컴포넌트 ui만 개발해보았습니다.
closes #25
=> #25 - Feat:상품 등록 컴포넌트 개발

src/App.jsx, src/components/follow/FollowingCard.jsx, src/components/follow/FollowingContainer.jsx, src/components/follow/FollowingHeader.jsx, src/pages/feed/FollowerList.css, src/pages/feed/FollowingList.css, src/pages/feed/FollowingList.jsx, src/pages/feed/MyProfile.jsx
=> #40 - Feat:팔로잉페이지 개발

src/components/Join.css, src/components/Join.jsx, src/components/LoginButton.css, src/components/LoginButton.jsx
=> #47-Feat:이메일로그인과 회원가입 개발

src/components/TapMenu.css, src/components/TapMenu.jsx
태그 변경 시 css 깨졌던 부분 수정했습니다!
close #57
=> #57 - Style: 태그변경으로인한css수정

src/pages/LoginEmail.css, src/pages/LoginEmail.jsx
=> #49-Feat:로그인 화면 합쳐집니다

src/components/follow/FollowHeader.jsx, src/components/follow/FollowingHeader.jsx, src/pages/feed/FollowerList.css
follow class명 변경했습니다.
closes #59
=> #59-Design : follow classname변경

src/assets/upload-file.svg, src/components/ProfileForm.css, src/components/ProfileForm.jsx, src/pages/ProfileSettingPage.css, src/pages/ProfileSettingPage.jsx
프로필 설정 페이지 개발 완료했습니다.(오늘 정신이 없어서 이제 올리네요..)
이부분이 ProfileForm 컴포넌트 입니다.
프로필 수정 부분 생각하면서 컴포넌트화 했습니다.(저기서 프로필 이미지랑 파일 업로드 부분도 컴포넌트 해야해요...!)
경고 문구는 일단 만들었다는 거 보기 쉽게 display: block 상태이고, 기본은 none으로 할 생각입니다.
**Q.** 경고 문구 부분 태그 고민하다가 strong으로 했는데.. 그냥 가도 될까요(아니면 의미없는 span이나 div로 할 생각입니다~)
close #42
=> #42 - Feat: 프로필 설정 페이지 개발

src/pages/Joinmembership.jsx
=> #50-Feat:회원가입개발 합쳐집니다

src/components/TapMenu.css, src/components/chat/TopChatNav.css, src/pages/HomePage.css, src/pages/chat/ChatListPage.css, src/pages/chat/ChatListPage.jsx
=> #61 - Design: 채팅페이지조합

src/pages/EditProfile.css, src/pages/EditProfile.jsx, src/pages/feed/Search.css, src/pages/feed/Search.jsx
EditProfile, Search 페이지 생성 했습니다.
close #62
=> #62 - Feat: EditProfile, Search 페이지 생성

src/components/Splash.jsx
setTimeout을 이용하여 splash 화면에서 로그인화면으로 변경될수 있게  작성하였습니다!
=> #74-Feat:setTimeout을 이용하여 Splsh 화면에서 로그인화면으로 변경

src/components/UploadFileBtn.css, src/components/UploadFileBtn.jsx, src/components/chat/ChatComment.css, src/components/chat/ChatComment.jsx, src/components/profile/ProfileForm.css, src/components/profile/ProfileForm.jsx, src/pages/SetProfile.css, src/pages/SetProfile.jsx, src/pages/feed/ProductUpload.css, src/pages/feed/ProductUpload.jsx, src/pages/feed/UploadPost.css, src/pages/feed/UploadPost.jsx
파일 업로드 버튼 컴포넌트화하고
사용하는 파일들에 컴포넌트 반영했습니다!
green36 (36*36) <br>
green50 (50*50) <br>
gray36   (36*36) <br>
close #75
=> #75 - Refactor: 파일 업로드 버튼 컴포넌트화 및 사용 파일 변경

src/pages/intro.css, src/pages/intro.jsx
splash 화면에서 로그인 화면으로 변경할 수 있는 페이지 작성 하였습니다.
=> #39-Feat:splash 화면에서 로그인화면으로 변경

src/components/button/UploadFileBtn.jsx, src/pages/UploadPost.jsx, src/pages/style/UploadPost.css
게시글 업로드시 텍스트를 POST 요청으로 보내는 부분 완료했습니다..!
사진 업로드 하는 부분은 따로 이슈 올리겠습니다.
(콘솔 찍어본건 추후에 기능 개발 완료되면 일괄적으로 지우겠슴다)
=> #79 - Feat: 게시글 텍스트 업로드

src/components/profile/ProfileInfo.jsx, src/pages/MyProfile.jsx
axios를 사용하여 내 프로필 정보를 불러왔습니다.
useEffect를 사용하다보니 변경사항이 없으면 아무런 데이터를 불러오지 못하고 있습니다 ㅜㅜ 고치도록 하겠습니다.
closes #84
=> #84 - Feat:axios를 사용하여 내프로필정보를 불러왔습니다

src/pages/UploadPost.jsx
이미지 3장까지 업로드 가능하도록 기능 구현했습니다.
close #85
=> #85 - Feat: 이미지 post 요청 기능

src/pages/UploadPost.jsx, src/pages/style/UploadPost.css
게시글 업로드 페이지의 이미지 미리보기 기능 추가했습니다!
**포함된 사항**
- 입력받은 이미지와 텍스트 모두 없을 때 업로드 버튼 누를시 경고창 뜨며 업로드 불가
- 이미지 3장 초과해서 업로드시 경고창 뜨며 추가적인 업로드 불가 (경고창은 뜨지만 업로드는 가능했던 이전 버전의 오류를 이번에 수정했습니다)
- 이미지 확장자명 예외처리
**추가할 사항**
- 업로드 버튼 클래스명 `disabled` 동적으로 조작하기
- 이미지 `input` 전혀 없을 때 스크롤바 없애기
- 두번째 이미지 추가시 첫번째 이미지 가로폭 줄어드는 현상 (ㄱ-...)
(기본적인 CRUD 기능 구현 후 수정하면 좋을 것 같습니다..!)
close #94
=> #94 - Feat: 이미지 미리보기 기능

src/components/post/Like.jsx, src/components/post/PostItem.css, src/components/post/PostItem.jsx, src/components/post/PostList.jsx, src/pages/MyProfile.jsx
프로필 화면에서 내가 쓴 글 리스트를 보여지게 만들었습니다.
이후 추가 할 것
- 앨범형 리스트 만들기
- 시간의 형식 바꾸기
closes #89
=> #89 - Feat:프로필에서 내가 쓴 글 리스트

src/App.jsx, src/components/loginjoin/IdPwForm.css, src/pages/Join.jsx
회원가입 페이지 중 Join.jsx 페이지 완성했습니다.
* 구현 기능
1. 처음 들어가면 누르면 커서가 설정됨
2. 이메일 주소 또는 비밀번호를 입력하고 입력창에서 포커스를 잃으면 바로 유효성 검사가 진행되고 통과하지 못한 경우 경고 문구가 각 입력창 하단에 표시.
3. 작성이 완료된 후, 유효성 검사를 통과할 경우 다음 버튼이 활성화되며, 버튼을 클릭하면 프로필 설정 폼이 나타남.
close #91
=> #91 - Feat: 회원가입 Join 페이지 기능 구현

src/components/modal/PostAlert.jsx, src/components/modal/PostModal.jsx
모달, 알림창 경로가 어떻게 될지 몰라서 일단은 props로 게시글 id 내려주는 구조로 짰고
게시글 업로드해서 받아온 id로 삭제 여부 확인 마쳤습니다!
close #99
=> #99 - Feat: 게시글 삭제 기능

src/components/profile/ProfileForm.jsx
프로필 설정 유효성 검사 기능만 완료했습니다.
사진 등록, 회원가입 API 추가 후 PR 올릴 예정입니다!
close #95
=> #95 - Feat: 회원가입-SetProfile 유효성 검사 기능

src/App.jsx, src/components/post/PostItem.jsx, src/components/profile/MyProfileBtn.jsx, src/pages/MyProfile.jsx, src/pages/UploadProduct.jsx, src/pages/style/UploadProduct.css
상품등록을 하고 있습니다
내프로필 페이지에서 상품등록을 연결해놨습니다.
api는 이미지 처리때문에 아직 미완이고
유효성 검사도 진행중입니다.
closes #88
=> #88 - Feat:상품등록 페이지 연결 + api 연결(미완) + 유효성검사(미완)

src/App.jsx, src/components/modal/PostModal.jsx, src/pages/EditPost.jsx
=> #103 - Feat: 게시글 수정 기능

src/components/post/PostList.jsx, src/components/product/ProductCard.jsx, src/components/product/ProductContainer.css, src/components/product/ProductContainer.jsx, src/pages/MyProfile.jsx
프로플에서 판매중인 상품 리스트를 볼 수 있게 만들었습니다.
closes #107
=> #107 - Feat:프로필에 상품리스트 설정

src/App.jsx, src/components/comment/PostCommentInput.jsx, src/components/modal/PostAlert.jsx, src/components/post/PostItem.css, src/components/post/PostItem.jsx, src/pages/EditPost.jsx, src/pages/Post.jsx, src/pages/UploadPost.jsx, src/pages/UploadProduct.jsx
댓글 버튼 클릭시 상세 페이지로 이동해 렌더링하는 기능 구현했습니다
close #111
=> #111 - Feat: 게시글 상세 페이지

src/App.jsx, src/components/modal/ReportPostModal.jsx, src/components/modal/profileModal.css, src/pages/EditPost.jsx, src/pages/Post.jsx
타인 게시글 신고할 수 있는 기능 추가했습니다!
close #110
=> #110 - Feat: 게시글 신고 기능

src/components/common/BasicProfileImg.jsx, src/components/profile/ProfileForm.jsx
프로필 설정 페이지에 프로필 이미지 등록 기능 구현했습니다.
BasicProfileImg 컴포넌트에 scr도 props로 받게 했습니다!
close #105
=> #105 - Feat: 프로필 이미지 등록 기능

src/components/common/TopBasicNav.jsx
땡땡땡버튼을 눌렀을 경우 로그아웃, 설정 모달창이 뜨도록 작성했습니다
=> #98 - Feat:점버튼을 누르면 로그아웃 모달로 연결

src/components/post/PostAlbum.css, src/components/post/PostAlbum.jsx, src/components/post/PostAlbumItem.css, src/components/post/PostAlbumItem.jsx, src/pages/MyProfile.jsx, src/pages/style/MyProfile.css
프로필 페이지에서 사진이 있는 게시글만 볼 수 있는 앨범형 게시글 리스트를 만들어보았습니다. 
closes #126
=> #126 - Feat:앨범형 게시글

src/components/chat/TopChatNav.jsx
채팅방에서 점 버튼을 누르면 채팅방을 나갈수 있는 모달을 연결했습니다!
=> #120 - Feat:채팅방에서 채팅방나가기를 모달로 연결

src/components/comment/PostComment.jsx, src/components/modal/CommentModal.jsx
댓글을 적었을 경우 점 버튼을 눌러 신고하기 모달을 연결하였습니다 
close #122
=> #122 - Feat:댓글자의 점 버튼을 눌러 신고하기를 모달로 연결

src/pages/EditPost.jsx, src/pages/UploadPost.jsx
게시글 업로드, 수정 페이지에서 텍스트, 이미지 여부에 따라서 버튼 활성화하는 기능 추가했습니다.
close #123
=> #123 - Feat: 업로드 버튼 활성화

src/components/profile/ProfileInfo.jsx, src/pages/MyProfile.jsx
프로필 클릭 시 바로 프로필 정보가 뜨지 않는 오류를 수정했습니다! 
closes #131
=> #131 - Fix:프로필 오류 수정

src/components/modal/Alert.css, src/components/modal/Modal.css, src/components/modal/ProductAlert.jsx, src/components/modal/ProductModal.jsx, src/components/modal/profileModal.css, src/components/post/PostAlbum.jsx, src/components/post/PostItem.jsx, src/components/product/ProductCard.css, src/components/product/ProductCard.jsx, src/components/product/ProductContainer.jsx, src/pages/MyProfile.jsx
=> #115 - Feat:상품모달연결

src/App.jsx, src/components/product/ProductContainer.jsx, src/components/profile/ProfileInfo.jsx, src/pages/FollowerList.jsx, src/pages/FollowingList.jsx
팔로잉, 팔로우 페이지 연결했습니다.
closes #135
=> #135 - Feat:팔로우,팔로잉페이지 연결

src/components/modal/LogoutModal.jsx, src/components/modal/PostAlert.jsx, src/components/modal/PostModal.jsx, src/components/modal/ProfileModal.jsx, src/components/modal/ReportPostModal.jsx
=> #138 - Refactor:modal, alert css명 변경때문에 코드수정

src/components/modal/ProductAlert.jsx
상품 삭제 기능을 개발했습니다!
상품을 클릭하면 modal창이 열리고 alert창이 열립니다.
삭제 버튼 클릭하면 삭제가 됩니다.
closes #137
=> #137 - Feat:상품 삭제 기능

src/assets/icon/close.svg, src/pages/UploadPost.jsx, src/pages/style/UploadPost.css
게시글 업로드 페이지에서 이미지를 다시 삭제할 수 있는 기능을 구현했습니다.
수정 페이지에서는 기존 이미지, 새로운 이미지를 다른 방식(전자는 mandarin~붙은 주소)으로 불러오고 있는데,
이 방식을 통일해야 같은 로직을 적용할 수 있을 것 같습니다! 
이 부분은 더 고민해보겠습니다.
close #129
=> #129 - Feat: 이미지 삭제 기능

src/App.jsx, src/components/profile/ProfileForm.jsx, src/pages/Join.jsx, src/pages/Register.jsx, src/pages/SetProfile.jsx, src/pages/style/SetProfile.css
회원가입에 필요한 남은 기능들을 모두 완료해 회원 가입부분 완성했습니다.
- 회원가입 API
회원가입에 필요한 모든 정보를 한 번에 전송하기 위해 state를 끌어올리는 방법을 사용했습니다.
Join.jsx에 있는 이메일, 비밀번호는 Register.jsx(새롭게 만들어짐)로 끌어올려서 SetProfile.jsx로 내려주었고
ProfileForm.jsx에 있는 사용자 이름, 계정 ID, 소개, 프로필 이미지는 SetProfile.jsx로 올려주었습니다.
- SetProfile.jsx의 ‘연두마켓 시작하기’ button을 Link 태그로 변경
- 모든 필수 정보 입력 시 회원가입 버튼 활성화
- 활성화 버튼 클릭 시 Home.jsx로 이동
콘솔은 추후 모두 삭제 하겠습니다..!
close #118
=> #118 - Feat: 회원가입 완성

src/pages/Login.jsx
로그인 페이지 코드 지저분했던 것을 좀 정리했습니다.
그리고 로그인 페이지에서 경고 문구라던가 방식이 갑자기 고민되네요..
월요일 회의 때 의견 여쭤 보겠습니다...!
close #144
=> #144 - Style: 코드 정리

src/components/post/PostItem.jsx, src/pages/EditPost.jsx, src/pages/UploadPost.jsx
업로드, 수정 페이지에서 이미지 경로 수정했습니다,
close #147
=> #147 - Fix: 이미지 경로 수정

src/pages/Login.jsx
페이지 내에서만 컴포넌트로 바뀌던 걸 주소로 이동시켰습니다.
close #152
=> #152 - Fix: /home으로 이동

src/components/product/ProductCard.jsx, src/pages/UploadProduct.jsx
상품의 가격을 천단위마다 콤마를 찍었습니다.
closes #148
=> #148 - Feat:상품의 가격을 천단위마다 콤마

src/components/comment/PostComment.css, src/components/post/PostItem.css, src/components/post/PostItem.jsx, src/pages/Post.jsx, src/pages/style/Post.css
게시글별 상세 페이지 불러오도록 작업했습니다.
댓글은 추후 기능 구현 후 추가될 예정이며 지금은 샘플 댓글 하나씩만 넣어두었습니다.
close #150
=> #150 - Feat: 게시글 상세 페이지

src/components/product/ProductCard.jsx, src/pages/MyProfile.jsx, src/pages/UploadProduct.jsx
=> #151 - Fix:상품 이미지 경로 수정

src/components/post/PostAlbum.css, src/components/post/PostAlbumItem.jsx
=> #156 - Fix:앨범형 게시글 리스트 이미지 경로 수정

src/components/post/PostAlbum.css, src/components/post/PostList.jsx, src/components/post/postList.css
css 변경했습니다!
마지막 게시글과 tap메뉴가 겹쳐서 보이지 않는 현상이 일어나길래 변경했습니다
closes #160
=> #160 - Feat:프로필페이지에서 TapMenu css 변경

src/components/post/PostAlbumItem.css, src/components/post/PostAlbumItem.jsx
프로필 페이지에서 앨범형 게시물을 클릭시 상세페이지로 넘어갈수 있도록 만들었습니다.
closes #157
=> #157 - Feat:앨범형 게시글 리스트 상세페이지 연결

src/components/comment/PostComment.jsx, src/components/comment/PostCommentInput.jsx, src/components/post/Like.jsx, src/components/post/PostItem.jsx, src/pages/EditPost.jsx, src/pages/Post.jsx, src/pages/UploadPost.jsx
- Post
- PostItem
- PostComment
- PostCommentInput
- Like
- UploadPost
- EditPost
위 jsx 파일에 ir 추가했습니다. 
태그 애매한 부분은 감귤마켓 참고했습니다!
`<BasicProfileImg>`, `<TopMenuComponent/>` 컴포넌트들도 하위에 사용됐는데 다른 파일들에서도 사용되기 때문에
통일한 뒤에 일괄 작업하면 될 것 같아 일단은 건드리지 않았습니다.
close #163
=> #163 - Feat: 게시글 관련파일 IR 추가

src/App.jsx, src/components/common/TopMenuComponent.css, src/components/common/TopMenuComponent.jsx, src/components/profile/MyProfileBtn.jsx, src/components/profile/ProfileForm.css, src/components/profile/ProfileForm.jsx, src/pages/EditProfile.jsx, src/pages/SetProfile.jsx
프로필 수정 기능 구현 완료했습니다..(?)
- MyProfile에서 프로필 수정 누르면 이동
- accountname은 수정 불가
*** 현재 사진 업로드 정상적으로 되지 않는 것을 확인했습니다..오전에 수정하겠습니다....
콘솔은 추후에 지우겠습니다.
close #143
=> #143 - Feat: 프로필 수정 기능

src/components/common/TopBasicNav.css, src/components/common/TopBasicNav.jsx, src/components/modal/Modal.css, src/components/modal/ProfileModal.jsx
로그아웃 여부 Alert 연결하였습니다!
이후 스타일도 함께 조정하였습니다!
close #133
=> #133 - Feat:로그아웃 여부 Alert 연결

src/components/chat/LeaveChatModal.css, src/components/chat/LeaveChatModal.jsx, src/components/chat/TopChatNav.jsx, src/components/common/TopMenuComponent.css
채팅방에서 나기기 모달 스타일을 밑으로 내리고 배경은 어둡게 했습니다~!
close #170
=> #170 - Design:모달 스타일 변경

src/App.jsx
"/" 경로로 접근했을 경우, 토큰이 있으면 "/home"으로 이동하게 했습니다.
close #171
=> #171 - Feat: 토큰 유무에 따른 자동로그인 기능 추가

src/App.jsx, src/components/modal/ProductModal.jsx, src/components/product/ProductContainer.css, src/pages/EditProduct.jsx
=> #168 - Feat:상품 수정

src/components/profile/ProfileForm.jsx, src/pages/SetProfile.jsx
회원가입 완료 시 로그인 페이지로 이동하게 하였고
버튼 부분을 수정했습니다
close #179
=> #179 - Fix: 회원가입 완료 시 로그인 페이지로 이동 및 버튼 수정

src/components/post/PostAlbum.jsx, src/components/post/PostList.jsx, src/components/product/ProductContainer.jsx, src/pages/UploadProduct.jsx
상품 등록 시 이미지, 상품명, 가격, 주소를 모두 작성해야 클릭 할 수 있게 css변경했습니다. 
+ 프로필페이지에서 상품, 게시글 없을 시 null을 추가했습니다.
closes #177
=> #177 - Feat:상품등록 버튼 disabled + 프로필 정보없을실 null

src/components/post/PostItem.css
스크롤로 이미지 모두 보이게 했습니다...
close #178
=> #178 - Feat: 복수 이미지 게시글 아이템

src/components/post/PostItem.jsx
포맷팅하는 함수(formatDate) 작성했습니다.
이미지 관련 코드들은 이전 PR에 같이 커밋을 못해서 같이 푸쉬했습니다...!
다음부터는... 잘 분리해서 PR 올리도록 하겠습니다...
close #183
=> #183 - Feat: 게시글 작성일 포맷팅

src/components/comment/PostCommentInput.jsx, src/pages/EditPost.jsx, src/pages/UploadPost.jsx
게시글 업로드, 수정 페이지와 게시글 상세 페이지의 댓글 입력란에서 `BasicProfileImg` 컴포넌트를 사용해 다음과 같이 뜨도록 했습니다.
- 프로필 이미지 있을 때: 사용자가 설정한 이미지
- 프로필 이미지 없을 때: 기본 이미지
close #189 
(이미지 하나 불러오는 데 작성되는 코드 양이 많아서 추후 리팩토링이 꼭 필요할 것 같습니다)
=> #189 - Feat: 작성자 프로필 이미지

src/pages/EditPost.jsx
수정 페이지에 이미지 삭제 기능 추가했습니다.
close #146
=> #146 - Feat: 게시글 이미지 수정

src/pages/Home.jsx, src/pages/MyProfile.jsx
token없을때 로그인창으로 이동하는 기능을 만들어보았습니다,
closes #192
=> #192 - Feat:token없을시 로그인창으로 이동

src/components/modal/Modal.css, src/components/modal/PostAlert.jsx, src/components/modal/PostModal.jsx, src/components/post/PostItem.jsx
게시글을 작성 후 점버튼을 누르면 수정 및 삭제 모달을 연결하였습니다!
close #173
=> #173 - Feat:게시글 수정 및 삭제 모달 연결

src/components/follow/FollowingCard.jsx, src/components/follow/FollowingContainer.jsx, src/components/profile/ProfileInfo.jsx, src/pages/FollowingList.jsx
팔로잉 리스트 api연결했습니다.
closes #196
=> #196 - 팔로잉 리스트 api 연결

src/components/common/TapMenu.jsx, src/components/follow/FollowerCard.jsx, src/components/follow/FollowerContainer.jsx, src/pages/FollowerList.jsx
=> #198 - 팔로우리스트 api 연결

src/components/profile/ProfileForm.jsx, src/pages/EditProfile.jsx, src/pages/SetProfile.jsx
프로필 이미지 수정 시 미리보기와 업로드가 제대로 되지 않던 현상 해결했습니다..!
close #175
=>  #175 - Fix: 프로필 이미지 수정 가능

src/components/comment/PostComment.css, src/components/comment/PostComment.jsx, src/components/comment/PostCommentInput.jsx, src/pages/Post.jsx
댓글 작성 기능 구현했습니다.
기본값으로 10개만 불러오고 있는데 10개를 초과했을 때 기능은 추후에 쿼리 스트링을 이용해 추가하겠습니다!
close #194
=> #194 - Feat: 게시글 댓글 작성 기능

src/App.jsx, src/components/follow/FollowingCard.jsx, src/components/post/PostItem.jsx, src/components/profile/ProfileBtn.jsx, src/components/profile/ProfileInfo.jsx, src/components/profile/UserProfileBtn.css, src/pages/MyProfile.jsx
유저 프로필 연결을 했습니다.
내프로필이 아니면 현재는 프로필수정/상품등록이 아닌 팔로우 버튼이 뜨게 만들어놨습니다.
closes #201
=> #201 - 유저 프로필 연결

src/components/modal/PostAlert.jsx, src/components/modal/PostModal.jsx, src/components/post/PostItem.jsx
=> #205 - 게시글 삭제 alert 연결

src/components/modal/PostAlert.jsx, src/components/modal/PostModal.jsx, src/components/post/PostItem.css, src/components/post/PostItem.jsx
수정, 삭제 기능 동작하도록 코드 수정했습니다.
close #204
=> #204 - Fix: 게시글 모달 기능 수정

src/components/comment/PostCommentInput.jsx, src/components/modal/PostAlert.jsx, src/components/modal/PostModal.jsx, src/components/post/PostItem.jsx, src/pages/EditPost.jsx, src/pages/Post.jsx, src/pages/UploadPost.jsx
- Post
- PostItem
- PostCommentInput
- UploadPost
- EditPost
- PostModal
- PostAlert
위 7개 파일에서 핸들러명을 `handle~`로 통일해 수정했습니다.
테스트 과정에서 보니까 업로드, 수정 후 이동하는 myprofile 라우터가 변경돼서 같이 수정했습니다.
close #208
=> #208 - Rename: 핸들러명 통일

src/pages/EditPost.jsx
게시글 수정 페이지에서 다시 유저 프로필 이미지를 불러왔습니다.
close #214
=> #214 - Fix: 수정 페이지 유저 프로필 불러오기

src/components/common/TopMenuComponent.css, src/components/modal/Modal.css, src/components/modal/PostModal.jsx, src/components/post/PostItem.jsx, src/pages/style/Splash.css
Splash 글자가 보일수 있게 조정하였습니다
뒤로가기 버튼 뒤에 follower 글자가 옆에 없어서 수정하였습니다
close #186
=> Design/#186/splash follower글자변경

src/components/profile/ProfileInfo.jsx, src/components/profile/UserProfileBtn.css, src/components/profile/UserProfileBtn.jsx, src/pages/FollowerList.jsx, src/pages/FollowingList.jsx
팔로우 버튼을 클릭시 팔로우가 되고, 언팔로우 버튼 클릭시 언팔로우가 됩니다
아직 버튼이 왔다갔다 하지는 못하고 있습니다..
closes #217
=> #217 - 팔로우, 언팔로우 api연결

src/App.jsx, src/components/product/ProductContainer.jsx, src/components/profile/ProfileInfo.jsx, src/pages/FollowerList.jsx, src/pages/FollowingList.jsx, src/pages/MyProfile.jsx
로그인 한 유저를 팔로우, 팔로잉 한 사람들의 팔로우, 팔로잉 리스트가 보이지 않았었습니다.
팔로워들의 프로필에서 그 팔로워를 팔로잉 한사람들의 리스트가 로그인한 유저의 팔로잉 리스트로 똑같이 보였기 때문에 수정했습니다..(말이 이상한것 같지만,,)
closes #220
=> #220 - 팔로잉, 팔로우 정보 리스트 불러오기

src/components/common/TopBasicNav.jsx, src/components/modal/LogoutModal.jsx, src/components/modal/ProfileModal.jsx
로그아웃 기능 구현했습니다.
로그인 할 때 받았던 localstorage에 있는 것들을 모두 삭제 했습니다.
closes #226
=> #226 - 로그아웃 기능 구현

src/components/chat/LeaveChatModal.jsx, src/components/chat/TopChatNav.jsx
=> #230 - Fix:채팅창 토글이 안닫히는 현상 변경

src/assets/icon/icon-post-album-off.svg, src/assets/icon/icon-post-album-on.svg, src/assets/icon/icon-post-list-off.svg, src/assets/icon/icon-post-list-on.svg, src/pages/MyProfile.jsx
png이미지 svg로 변경했습니다.
closes #235
=> #235 - 앨범형, 리스트형 이미지 svg로 변경

src/components/follow/FollowerCard.jsx, src/components/follow/FollowingCard.jsx, src/pages/style/FollowerList.css
팔로잉, 팔로잉 리스트 이미지 사이즈 조절했습니다
objext-fit으로 해결안되는 이미지들이 있어서 div로 한번 감싸주고 했습니다.
closes #237
=> #237 - 팔로우, 팔로잉 리스트 이미지 사이즈 조절

src/components/comment/PostCommentInput.css, src/pages/style/Post.css
댓글 가려지는 현상 수정하고 댓글 input에 `border-top` 추가했습니다.
close #243
=> #243 - Fix: 댓글 가림 현상 수정

src/components/loginjoin/IdPwForm.css, src/pages/Join.jsx, src/pages/Register.jsx
비밀번호 확인 input을 추가하였습니다.
close #245
=> #245 - Feat: 비밀번호 확인 input 추가

src/pages/style/FollowerList.css
팔로우, 팔로잉 리스트 프로필 소개가 길어지면 말줄임으로 변화시켰습니다.
closes #253
=> #253 - Feat:팔로우, 팔로잉 리스트 프로필 소개 말줄임

src/pages/Home.jsx, src/pages/style/Home.css
기존 상태에서
이렇게 되도록 해결했습니다!
close #252
=> #252 - Fix: 세로 창  축소 시 상단바로 글자 올라오는 현상 해결

src/components/modal/PostAlert.jsx, src/components/modal/PostModal.jsx, src/components/post/PostItem.jsx
타인의 게시글일 때는 신고 모달이 나오도록 기능 추가했습니다.
close #247
=> #247 - Feat: 게시글 신고 기능

src/App.jsx, src/components/product/ProductCard.jsx
로그인 한 유저가 다른 유저의 상품 클릭시 404페이지로 이동하게 했습니다.
closes #262
=> #262 - 유저의 상품 클릭시 404페이지로 이동

src/pages/MyProfile.jsx
유저프로필에서 프로필 버튼 클릭시 마이페이지로 이동할 수 있게 고쳤습니다!
closes #264
=> #264 - 유저프로필에서 프로필버튼 클릭 시 마이페이지로 이동

src/pages/EditProduct.jsx
상품 수정 버튼을 'saveBtn on'으로 변경했습니다.
closes #268
=> #268 - Fix:상품수정 저장 버튼 변경

src/components/search/UserList.jsx, src/pages/Search.jsx
검색 후 나온 결과를 클릭 시 해당 프로필로 이동하도록 했습니다!
(커밋 메세지 수정하려고 했는데요...수정하다가..네..죄삼다..)
close #260
=> #260- Feat: 검색결과 클릭 시 해당 프로필로 이동

src/pages/MyProfile.jsx, src/pages/NotFound.jsx, src/pages/Post.jsx, src/pages/loading.jsx, src/pages/style/404loading.css
일단 있는 아이콘으로 간단하게 ... 만들었습니다.
게시글 상세 페이지, 프로필 화면으로 이동할 때 나오는 화면이고,
404때 쓰였던 css를 공유하고 있어서 기존 파일명을 `NotFound.css`에서 `404Loading.css`로 변경했습니다.
close #274
=> #274 - Feat: 로딩 페이지 추가

src/components/comment/PostComment.jsx, src/components/post/PostItem.jsx
`PostItem`과 `PostComment` 컴포넌트에서 작성자 이름과 이미지 클릭시 해당 유저의 프로필로 이동하는 기능을 추가했습니다.
close #272
=> #272 - Feat: 작성자 프로필 이동 기능

src/components/loginjoin/LoginButton.css, src/components/modal/Alert.css, src/components/modal/Modal.css
로그인 페이지, 모달에 애니메이션을 적용했습니다.
close #279
=> #279 - Feat: 애니메이션 적용

src/components/profile/ProfileForm.jsx, src/pages/EditProfile.jsx
=> #283 - Fix: 프로필 수정 기능 수정

src/pages/Home.jsx, src/pages/Intro.jsx, src/pages/NotFound.jsx, src/pages/Splash.jsx, src/pages/loading.jsx, src/pages/style/Splash.css
완두콩 아이콘이 쓰인 파일에서 출처를 주석으로 표시했습니다.
close #285
=> #285 - Comment: 아이콘 출처 표기

src/components/chat/ChatItem.css, src/pages/ChatList.jsx, src/pages/EditPost.jsx, src/pages/UploadPost.jsx, src/pages/style/ChatList.css, src/pages/style/UploadPost.css
모바일 어떤 모델 기준까지 맞출지 정하진 않아서 
일단은 개발자도구 상으로 4번째 모델까지 UI 깨졌던 현상 수정했습니다. (채팅리스트, 게시물 작성/수정 페이지)
내용 수정하면서 import한 모듈 순서도 수정했습니다.
close #286
=> #286 - Fix: 모바일 UI 수정

src/components/profile/UserProfileBtn.jsx, src/pages/MyProfile.jsx
유저 프로필에서 버튼 클릭시 팔로우, 언팔로우 변화를 나타내었습니다.
- 팔로우 카운터는 새로고침을 해야 반응이 되서 추후에 고치겠습니다,,
closes #298
=> #298 - Fix:유저 프로필 팔로우, 언팔로우 버튼 변화

src/components/profile/ProfileForm.jsx, src/pages/EditProfile.jsx
네... 드디어 프로필 수정 에러 해결했습니다~!
한 번 클릭에 모두가 제대로 저장됩니다.
콘솔도 같이 제거 했습니다!
close #301
=> #301 - Fix: 저장버튼 에러 해결 및 콘솔 제거

src/components/follow/FollowerCard.jsx, src/components/follow/FollowingCard.jsx
팔로우, 팔로잉 리스트에서 내 프로필에 있는 팔로우, 취소 버튼을 제거했습니다.
closes #307
=> #307 - Feat : 팔로우, 팔로잉 리스트에서 내프로필 팔로우 버튼 삭제

src/components/button/UploadFileBtn.jsx, src/components/loginjoin/IdPwForm.jsx, src/components/loginjoin/LoginButton.jsx, src/components/profile/ProfileForm.jsx, src/pages/Join.jsx, src/pages/Login.jsx
처음에 API 쓴다고 풀어 헤쳐놨던 컴포넌트들 다시 사용했습니다!
close #309
=> #309 - Style: 컴포넌트 재조립
